- hosts: all
  sudo: yes
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: Install python2.7 so that Ansible can work
      raw: sudo apt-get -y update -qq && sudo apt-get -y install -qq python2.7 aptitude

#   tasks:
#     - name: 'ensure user {{ project_name }} exists'
#       user: name={{ project_name }} state=present

# - name: Install python2.7 so that Ansible can work
#   raw: "sudo apt-get -y update -qq && sudo apt-get -y install -qq python2.7 aptitude"
